### ISSUE TITLE
No api to resume chat from customer side by using chatjs?

### ISSUE THREAD

**Issue by ghost** [amazon-connect/amazon-connect-chatjs#1]
Hi, 

Is there any api can export to client that used to resume chat for customer side?

Thanks
Chengkun

**Comment by labelson** [comment]
Can you clarify what you mean by resume a chat? We have no "pause" chat functionality built in. Once a chat has ended, it is not possible to restart that chat. However, it is possible to initiate a new chat as the same customer (which re-enters the customer into the queue with a new contactId). Look into creating a disconnect flow contact flow. I believe there is a "sample disconnect flow" provided in the Admin Website by default.

If you want the customer to be able to recover from a misclick on an end chat button, I would recommend you to use a confirm modal in your implementation to ensure they want to permanently end the chat, or make it clear in some way that ending the chat is irreversible, and they likely will not get the same agent if they reenter the chat queue.

**Comment by ehills** [comment]
Hi @labelson,
I'm just going to jump on this thread although I suspect I have a slightly different question.
If a customer closes their browser before the chat is ended, do we simply call `chatSession.connect()` again with the same participantId? Or how does one reconnect to the chat without calling `chatSession.Create()`?

**Comment by tscheuneman** [comment]
Hi @ehills,

If you need to reconnect after a page reload, you should create a new chat session with the previous participant token, id, and contact id.  If the chat has been implicitly ended however, it won't be possible to reconnect.
