### ISSUE TITLE
Using amazon-connect-chat.js in a React compoent

### ISSUE THREAD

**Issue by indyfromoz** [amazon-connect/amazon-connect-chatjs#10]
I am building a React component that presents a custom chat interface to a customer. My aim is to use APIs available in `amazon-connect-chat.js` and documented in `README.md` in this repository like so - 

```
  componentDidMount() {
    connect.ChatSession.setGlobalConfig({
      region: AWS_CONNECT_REGION
    });
  }
```
In the React JSX file, I have tried importing the ChatJS file various ways such as - 

```
require("./amazon-connect-chat.js");
```

I am seeing errors when I run `yarn start` -- 

```
./src/components/App/amazon-connect-chat.js
  Line 1:1:       Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:157:     Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:265:     Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:1080:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:2654:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
```

Is there something I am missing in the setup of the ChatJS script?

**Comment by pmc-a** [comment]
@indyfromoz similar situation here, I've implemented it within a React application by pulling it in as an async script within my main HTML - which attaches it to the global window object. Alternatively, you could import the script outside the scope of a component and allow webpack to pick it up and bundle it up with the rest of your application.

Then I've used the Context API to hook it into the React engine and provide it throughout the application.

Hope this helps!

**Comment by ryanall** [comment]
Facing the same issues - ideally should be able to import this as a dependency in our project and call methods direct without needing to reference the bundle directly.

I think we'd all appreciate some further details in the README if this is at all possible 👍

**Comment by wilberh** [comment]
Please provide further details.  I don't have access to the global connect variable in my current scope after I import it in React.

**Comment by indyfromoz** [comment]
@wilberh  You may want to take a look at - https://github.com/pmc-a/aws-connect-client 
I ended up building a non-React solution for a custom chat component. I hope someone from Amazon Connect team helps developers build React Components with their Chat APIs.

**Comment by marcogrcr** [comment]
Note that `amazon-connect-chatjs` [has been released to `npm`](https://www.npmjs.com/package/amazon-connect-chatjs). The following minimal config works for me:

**index.jsx:**

```js
import "amazon-connect-chatjs";
import React, { Fragment } from "react";
import { render } from "react-dom";

function App() {
  const isLoaded = window.connect && window.connect.ChatSession;

  return (
    <Fragment>
      <h1>react-amazon-connect-chatjs</h1>
      {isLoaded ? "loaded!" : "failed"}
    </Fragment>
  );
}

render(<App />, document.getElementById("app"));
```

**index.html:**

```html
<!DOCTYPE html>
<html>
  <head>
    <title>react-amazon-connect-chatjs</title>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
```

**webpack.config.js:**

```js
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  entry: "./index.jsx",
  devServer: {
    https: true
  },
  module: {
    rules: [
      { test: /\.jsx?$/, use: "babel-loader" }
    ],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./index.html",
    }),
  ]
};
```

**.babelrc:**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "corejs": { "version": 3 }
      }
    ],
    "@babel/preset-react"
  ]
}
```

**package.json:**

```json
{
  "name": "amazon-connect-chatjs-react-demo",
  "version": "1.0.0",
  "scripts": {
    "start": "webpack-dev-server -w"
  },
  "dependencies": {
    "amazon-connect-chatjs": "1.0.6",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  },
  "devDependencies": {
    "@babel/core": "7.10.2",
    "@babel/preset-env": "7.10.2",
    "@babel/preset-react": "7.10.1",
    "babel-loader": "8.1.0",
    "core-js": "3.6.5",
    "html-webpack-plugin": "4.3.0",
    "regenerator-runtime": "0.13.5",
    "webpack": "4.43.0",
    "webpack-cli": "3.3.11",
    "webpack-dev-server": "3.11.0"
  }
}
```

---

I believe this can be closed.

**Comment by indyfromoz** [comment]
Closing this issue as ChatJS SDK is now available via NPN. Thank you @marcogrcr for sharing the approach 🙏
