### ISSUE TITLE
Expose CHAT_EVENTS.CONNECTION_LOST through ChatSession.onConnectionLost()

### ISSUE THREAD

**Issue by marcogrcr** [amazon-connect/amazon-connect-chatjs#116]
**Problem:**

Currently, the `ChatSession` API exposes two methods related to the underlying `WebSocket` connection(s)' health:

- `onConnectionBroken()`: Triggered when the underlying `WebSocket` connection has been broken or failed to be established (e.g. the `participantToken` is invalid).
- `onConnectionEstablished()`: Triggered when the underlying `WebSocket` connection has been established or re-established after being lost.

Internally, these methods subscribe to the `CHAT_EVENTS.CONNECTION_BROKEN` and `CHAT_EVENTS.CONNECTION_ESTABLISHED` events respectively.

https://github.com/amazon-connect/amazon-connect-chatjs/blob/6b2ee9219809cd5364d65bc33af1fd25cecc74f4/src/core/chatSession.js#L95-L101

Upon closer examination of the `CHAT_EVENTS` constant, there seems to be a useful `CHAT_EVENTS.CONNECTION_LOST` event as well.

https://github.com/amazon-connect/amazon-connect-chatjs/blob/6b2ee9219809cd5364d65bc33af1fd25cecc74f4/src/constants.js#L52-L66

During my tests, I was able to verify that the event gets triggered whenever the underlying `WebSocket` connection(s) get(s) closed, and once it's/they're re-established, the `onConnectionEstablished` (a.k.a. `CHAT_EVENTS.CONNECTION_ESTABLISHED`) event gets triggered.

One can currently subscribe to this event with the following code:

```ts
const session = connect.ChatSession.create(/* ... */);
session.controller.subscribe("CONNECTION_LOST", (event) => {
  const { chatDetails } = event;
  // notify user that they have temporarily lost the connection to the chat
});
```

However, this code is fragile as it depends on a private implementation detail that could change on a newer version.

**Proposal:**

Thus, I'm proposing that a new publicly documented method gets added to `class ChatSession` as follows:

**chatSession.js**

```ts
export class ChatSession {
  // (...)

  onConnectionLost(callback) {
    this.controller.subscribe(CHAT_EVENTS.CONNECTION_LOST, callback);
  }
}
```

**index.d.ts**

```ts
declare namespace connect {
  interface ChatSession {
    // (...)

    /**
     * Subscribes an event handler that triggers when the session connection is lost.
     * @param handler The event handler.
     */
    onConnectionEstablished(
      handler: (event: ChatConnectionLostEvent) => void
    ): void;
  }

  interface ChatConnectionLostEvent {
    readonly chatDetails: ChatDetails;
  }
}
```

**Comment by mhiaror** [comment]
Thanks..
Good suggestion, I can review and add support for this in next release for ChatJs.

**Comment by spencerlepine** [comment]
Released in latest version on npm: `amazon-connect-chatjs@1.4.0`
