### ISSUE TITLE
SendMessage from AgentChatSession by clicking through button.

### ISSUE THREAD

**Issue by nayabrasool4910** [amazon-connect/amazon-connect-chatjs#120]
I am trying to send message from AgentChatSession by clicking through button. 

I referred this article - https://docs.aws.amazon.com/connect-participant/latest/APIReference/API_SendEvent.html

I am not aware of ConnectionToken and ClientToken. If Anyone know, Please mention your valuable comments on how to send message through button from Agent side.

My Code :

sendMessage(){
  connect.contact((contact) => {
      contact.onAccepted(async () => {
          const cnn = contact.getAgentConnection() as connect.ChatConnection
          if(cnn){
          const agentChatSession = await cnn.getMediaController();
            agentChatSession.sendMessage({ message:'Good Morning' , contentType: 'text/plain' }).then((res) =>{
              console.log(res.status)
            })
          }

        });
    })
}

but its not sending message and not showing any response

Can anyone help me on this.

**Comment by nayabrasool4910** [comment]
I am trying this way also. but iam getting access denied error.

sendMessage(){
    const headers = new HttpHeaders({
      'X-Amz-Bearer': sessionStorage.getItem('token'), //participation Token
      'Content-Type':'application/json',

    });
    const requestOptions = { headers: headers };
    const body = {message: "so and so", contentType: "text/plain"}
    this.http.post('https://participant.connect.us-east-1.amazonaws.com/participant/message', body, requestOptions).subscribe({
        next: data => {
          this.postId = data
          console.log(this.postId)
      },
      error: error => {
          this.errorMessage = error.message;
          console.error('There was an error!', error);
      }     
      })
}

**Comment by nayabrasool4910** [comment]
This is another way I am trying to sending Message from agent side. but it's not giving any response.

Code :

messageOutro(){
  connect.contact((contact) =>{
    contact.onAccepted(async()=>{
      const cnn = contact.getAgentConnection() as connect.ChatConnection
      if(cnn){
        const agentChatSession =  await cnn.getMediaController();
        agentChatSession.onMessage((res) =>{
          console.log(res)
        })
        agentChatSession.sendMessage({message:'Hi Colleague, I will be helping you today, How can I assist?',contentType:'text/plain'})
      }
    })
  })
}

Please can I know the process to send message from AgentChatSession.

**Comment by mhiaror** [comment]
The code looks correct to me; for me below is working
```
sendMessage(){
connect.contact((contact) => {
contact.onAccepted(async () => {
...
 const agentConnection = contact.getAgentConnection();

agentConnection.getMediaController().then(controller => {
  controller.sendMessage({ message: content.data, contentType: content.type })
    .then(function (response) {
        console.log("Send message success", response);
        return response;
 }).catch(function (error) {
      console.log("Send message failure", error)
});


})

----------------
Response has data:
{"AbsoluteTime":"2023-02-24T00:32:00.608Z","Id":"d45de785-a3f4-4995-93fd-caedc2ce6670"}

```

If you have already created a prod widget - you can go to the `test-chat` page -> open inspector and see code implementation. 

![Prod Connect Instance screenshot](https://user-images.githubusercontent.com/107958541/221062824-1071bc46-6ab4-440a-8614-4227abef6828.png)

**Comment by marcogrcr** [comment]
Hello @nayabrasool4910:

Looking at your code

```ts
sendMessage() {
  connect.contact((contact) => {
    contact.onAccepted(async () => {
      const cnn = contact.getAgentConnection() as connect.ChatConnection
      if(cnn){
        const agentChatSession = await cnn.getMediaController();
        agentChatSession.sendMessage({ message:'Good Morning' , contentType: 'text/plain' }).then((res) =>{
          console.log(res.status)
        })
      }
    });
  })
}
```

Here's some things I would check:

**1\.** Ensure you're importing the libraries in the right order. `amazon-connect-chatjs` comes first, and `amazon-connect-streams` comes second:

If you're using `<script>` tags:

```html
<!-- "amazon-connect-chat.js" must come first -->
<script src="amazon-connect-chat.js"></script>

<!-- "connect-streams.js" or "connect-streams-min.js" comes second -->
<script src="connect-streams.js"><script>
```

If you're using es modules:

```ts
// amazon-connect-chatjs must come first
import "amazon-connect-chatjs";

// amazon-connect-streams comes second
import "amazon-connect-streams";
```

**2\.** Ensure the contact you receive is a chat contact:

```ts
sendMessage() {
  connect.contact((contact) => {
    if (contact.getType() != connect.ContactType.CHAT) {
      // do not continue as this is not a chat contact
      return;
    }

    contact.onAccepted(async () => {
      // now you can safely cast the agent connection as a ChatConnection
      const cnn = contact.getAgentConnection() as connect.ChatConnection
      // (...)
    });
  })
}
```

**3\.** Ensure you have initialized the CCP specifying a region. Looking at https://github.com/amazon-connect/amazon-connect-chatjs/issues/120#issuecomment-1441224670, it seems you're using `us-east-1`.

```ts
const containerDiv = /* (...) */;
connect.core.initCCP(containerDiv, {
  region: "us-east-1",
  // (...)
});
```

This is because the `region` parameter is used to initialize the `ChatSession` and it will default to `us-west-2` if you don't specify it. Here's the `amazon-connect-streams` source code as reference:

```js
//
// https://github.com/amazon-connect/amazon-connect-streams/blob/v2.4.5/src/core.js#L912-L952
connect.core.initCCP = function (containerDiv, paramsIn) {
  // (...)
  var params = {};
  if (typeof (paramsIn) === 'string') {
    params.ccpUrl = paramsIn;
  } else {
    params = paramsIn;
  }

  // (...)
  connect.core.mediaFactory = new connect.MediaFactory(params);
}

//
// https://github.com/amazon-connect/amazon-connect-streams/blob/v2.4.5/src/mediaControllers/factory.js#L21-L47
connect.MediaFactory = function (params) {
  // (...)
  var metadata = connect.merge({}, params) || {};
  metadata.region =  metadata.region || "us-west-2"; // Default it to us-west-2

  var getMediaController = function (connectionObj) {
    // (...)
    switch (connectionObj.getMediaType()) {
      case connect.MediaType.CHAT:
        return mediaControllers[connectionId] = new connect.ChatMediaController(connectionObj.getMediaInfo(), metadata).get();
        // (...)
  }
  // (...)
}

//
// https://github.com/amazon-connect/amazon-connect-streams/blob/v2.4.5/src/mediaControllers/chat.js#L21-L42
connect.ChatMediaController = function (mediaInfo, metadata) {
  // (...)
  var createMediaInstance = function () {
    connect.ChatSession.setGlobalConfig({
      // (...)
      region: metadata.region
    });

    // (...)
    var controller = connect.ChatSession.create({
      chatDetails: mediaInfo,
      type: "AGENT",
      websocketManager: connect.core.getWebSocketManager()
    });
    // (...)
    return controller
      .connect()
      .then(function (data) {
        // (...)
        return controller;
      })
      // (...)
  };
  // (...)
}
```

**4\.** If it still fails, consider obtaining a reference to the connection using a manual filter instead of the `getAgentConnection()` method:

```ts
sendMessage() {
  connect.contact((contact) => {
    // (...)
    contact.onAccepted(async () => {
      const cnn = contact.getConnections().find(cnn => cnn.getType() === connect.ConnectionType.AGENT);
      // (...)
    });
  })
}
```

The difference with this approach is that the `getAgentConnection()` has a more permissive filter (i.e. it allows `MONITORING` connections). Here's the `amazon-connect-streams` source code as reference:

```js
//
// https://github.com/amazon-connect/amazon-connect-streams/blob/v2.4.5/src/api.js#L854-L859
Contact.prototype.getAgentConnection = function () {
  return connect.find(this.getConnections(), function (conn) {
    var connType = conn.getType();
    return connType === connect.ConnectionType.AGENT || connType === connect.ConnectionType.MONITORING;
  });
};
```

**5\.** Finally, if this still fails, consider creating the `ChatSession` manually as well:

```ts
sendMessage() {
  connect.contact((contact) => {
    contact.onAccepted(async () => {
      const cnn = contact.getAgentConnection() as connect.ChatConnection
      if(cnn){
        const agentChatSession = connect.ChatSession.create({
          chatDetails: cnn.getMediaInfo(),
          options: {
            region: "us-east-1"
          },
          type: connect.ChatSession.SessionTypes.AGENT,
          websocketManager: connect.core.getWebSocketManager()
        });
        agentChatSession.sendMessage({ message:'Good Morning' , contentType: 'text/plain' }).then((res) =>{
          console.log(res.status)
        })
      }
    });
  })
}
```

The main difference here is that you're specifying the region directly to `create()`, rather than indirectly through `setGlobalConfig()`.

**Comment by marcogrcr** [comment]
@nayabrasool4910:

Also, looking at your in https://github.com/amazon-connect/amazon-connect-chatjs/issues/120#issuecomment-1441224670:

```ts
sendMessage(){
  const headers = new HttpHeaders({
    'X-Amz-Bearer': sessionStorage.getItem('token'), //participation Token
    'Content-Type':'application/json',
  });
  const requestOptions = { headers: headers };
  const body = {message: "so and so", contentType: "text/plain"}
  this.http.post('https://participant.connect.us-east-1.amazonaws.com/participant/message', body, requestOptions).subscribe({
    next: data => {
      this.postId = data
      console.log(this.postId)
    },
    error: error => {
      this.errorMessage = error.message;
      console.error('There was an error!', error);
    }     
  })
}
```

You're getting an access denied error because you're using the `participantToken` to send a message. You need to obtain a `connectionToken` first:

```ts
const baseUrl = "https://participant.connect.us-east-1.amazonaws.com";

async function getConnectionToken()/*: Promise<string> */{
  const { ConnectionToken, Expiry } = JSON.parse(sessionStorage.getItem("connectionCredentials") || "{}");

  // return the connection token if it exists and it has not expired
  if (Expiry && new Date() < new Date(Expiry)) {
    return ConnectionToken;
  }

  // get a new connection token as one does not exist or it has expired
  const res = await fetch(`${baseUrl}/participant/connection`, {
    // see: https://docs.aws.amazon.com/connect-participant/latest/APIReference/API_CreateParticipantConnection.html
    method: "POST",
    headers: {
      "X-Amz-Bearer": sessionStorage.getItem("token"), // participant token
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      Type: ["CONNECTION_CREDENTIALS"]
    })
  });

  // ensure we got a successful response
  if (!res.ok) {
    throw new Error(`Got ${res.status} response: ${await res.text()}`);
  }

  // store the new connection credentials
  const { ConnectionCredentials } = await res.json();
  sessionStorage.setItem("connectionCredentials", JSON.stringify(ConnectionCredentials));

  // return the connection token
  return ConnectionCredentials.ConnectionToken;
}
```

Also, you're sending the wrong body to the `SendMessage` operation, rather than
`{ message: "...", contentType: "..." }`, it should be `{ Content: "...", ContentType: "..." }`:

```ts
async function sendMessage()/*: Promise<void> */{
  // get the connection token
  const connectionToken = await getConnectionToken();

  // send the message
  const res = await fetch(`${baseUrl}/participant/message`, {
    // see: https://docs.aws.amazon.com/connect-participant/latest/APIReference/API_SendMessage.html
    method: "POST",
    headers: {
      "X-Amz-Bearer": connectionToken,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      ContentType: "text/plain",
      Content: "so and so"
    })
  });

  // ensure we got a successful response
  if (!res.ok) {
    throw new Error(`Got ${res.status} response: ${await res.text()}`);
  }

  console.log("Got response:", await res.json());
}
```

In general, it's recommended that you use the built-in Javascript AWS SDK clients, rather than manually constructing your requests. For example:

```ts
// v3
import {
  ConnectParticipantClient,
  CreateParticipantConnectionCommand,
  SendMessageCommand,
} from "@aws-sdk/client-connectparticipant";

async function sendMessage(): Promise<void> {
  const client = new ConnectParticipantClient({
    region: "us-east-1",
    credentials: { accessKeyId: "", secretAccessKey: "" },
  });
  const { ConnectionCredentials } = await client.send(
    new CreateParticipantConnectionCommand({
      ParticipantToken: sessionStorage.getItem("token"), // participant token
      Type: ["CONNECTION_CREDENTIALS"],
    })
  );
  const response = await client.send(
    new SendMessageCommand({
      ConnectionToken: ConnectionCredentials.ConnectionToken,
      ContentType: "text/plain",
      Content: "so and so",
    })
  );
  console.log("Got response:", response);
}
```

That being said, keep in min that the complexity of getting a `connectionToken` keeping track of its expiry, and most importantly, connecting to and managing the `WebSocket` connection to receive messages is the whole point of `amazon-connect-chatjs`, so it's recommended that you use this library instead of the AWS SDK.

**Comment by nayabrasool4910** [comment]
Hi @marcogrcr and @mhiaror, thanks for your response and great explanation.

I am using es module so I added amazon-connect-chatjs first and amazon-connect-streams second.

```
import "amazon-connect-chatjs";
import "amazon-connect-streams";
```
I am getting this error. I need to import aws-sdk here ?
core.js:4442 ERROR Error: Uncaught (in promise): TypeError: AWS.ConnectParticipant is not a constructor
TypeError: AWS.ConnectParticipant is not a constructor
    at new N (amazon-connect-chat.js:1:259504)
    at Object._createAwsClient (amazon-connect-chat.js:1:263628)
    at Object.getCachedClient (amazon-connect-chat.js:1:263441)
    at push.7X61.de.constructor._createChatController (amazon-connect-chat.js:1:376390)
    at push.7X61.de.constructor.createChatSession (amazon-connect-chat.js:1:376046)
    at Object.create (amazon-connect-chat.js:1:376590)
    at createMediaInstance (connect-streams.js:27189:1)
    at Object.get (connect-streams.js:27236:1)
    at getMediaController (connect-streams.js:27294:1)
    at Object.get (connect-streams.js:27316:1)
    at resolvePromise (zone-evergreen.js:798:1)
    at new ZoneAwarePromise (zone-evergreen.js:963:1)
    at __awaiter (tslib.es6.js:72:1)
    at Subscription.f (ccp.component.ts:165:40)
    at connect-streams.js:26414:1
    at Array.forEach (<anonymous>)
    at EventBus.trigger (connect-streams.js:26412:1)
    at Subscription.f (connect-streams.js:26430:1)
    at connect-streams.js:26414:1
    at Array.forEach (<anonymous>)


I added region : us-east-1 , connection is going to us-east-1 successfully.

My Code :

```

import "amazon-connect-streams";
import "amazon-connect-chatjs";

constructor(){

}
ngOnInit(): void {
    connect.core.initCCP(document.getElementById('containerDiv'), {
      loginUrl: environment.loginUrl,
      loginPopupAutoClose: true,
      ccpUrl: environment.ccpUrl,
      loginPopup: true,    
      softphone: {
        allowFramedSoftphone: true
      },
      region: "us-east-1",
      pageOptions: { 
        enableAudioDeviceSettings: true,
        enablePhoneTypeSettings: true
      }
    });
	
	
   connect.contact((contact) => {
    contact.onAccepted(async () => {
      const cnn = contact.getAgentConnection() as connect.ChatConnection
      if(cnn){
        const agentChatSession = await cnn.getMediaController();
        agentChatSession.sendMessage({ message:'Hi Colleague, I will be helping you today, How can I assist?' , contentType: 'text/plain' }).then((res) =>{
          console.log(res.status)
        })
      }
    });
  })


  sendMessage() {
  console.log('HI, ');
  console.log(connect.contact);
  connect.contact((contact) => {
    console.log(contact);
    contact.onAccepted(async () => {
      const cnn = contact.getAgentConnection() as connect.ChatConnection
      if(cnn){
        const agentChatSession = await cnn.getMediaController();
        agentChatSession.sendMessage({ message:'SO and SO' , contentType: 'text/plain' }).then((res) =>{
          console.log(res.status)
        })
      }
    });
  })


}

}
```

Without button I am able to send message successfully 'Hi Colleague, I will be helping you today, How can I assist?'.

![CCP1](https://user-images.githubusercontent.com/52395438/221346716-f584dcec-d263-48e8-af1a-758e5f56a448.png)

But By Cicking sendMessage() button I am able to print in console.

![button](https://user-images.githubusercontent.com/52395438/221347155-b2b1f743-8d5f-458f-a961-983d53b31206.png)

its not going inside the connect.contact and not printing console.log(contact) in console. I am facing issue here.

constructor is empty in my code. I need to add anything in constructor as global object in above code.

I did not try with connectionToken. I will try with connectionToken and I will update here the results. Thanks

**Comment by nayabrasool4910** [comment]
Hi @marcogrcr with button click I am able to send message using "@aws-sdk/client-connectparticipant";. Thanks for your response. 

Please check above comment and mention your valuable comment that any mistake I did above. I tried by button click can send message from AgentChatSession to CustomerChatSession with  'amazon-connect-chatjs' library

**Comment by marcogrcr** [comment]
Hi @nayabrasool4910:

> I am using es module so I added amazon-connect-chatjs first and amazon-connect-streams second.
> I am getting this error. I need to import aws-sdk here ?

Apologies for the confusion, the right order is `amazon-connect-streams` first, `amazon-connect-chatjs` second:

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/README.md?plain=1#L17-L22

If have updated https://github.com/amazon-connect/amazon-connect-chatjs/issues/120#issuecomment-1444222478 to reflect this.

---

> I added region : us-east-1 , connection is going to us-east-1 successfully.

I'm glad that adding the `region` parameter to the `connect.core.initCCP()` call made it work initially!

---

>But By Cicking sendMessage() button I am able to print in console.
> its not going inside the connect.contact and not printing console.log(contact) in console. I am facing issue here.

I see now. Your problem is caused by a misunderstanding/misuse of the `amazon-connect-streams` API, rather than `amazon-connect-chatjs`. And your question belongs in [amazon-connect/amazon-connect-streams](https://github.com/amazon-connect/amazon-connect-streams). That being said, I'm gonna answer anyway since all the context is in this issue already:

Notice what the documentation of [connect.contact()](https://github.com/amazon-connect/amazon-connect-streams/blob/12992a4832e1e6631b2b531123c7419491b0dc87/Documentation.md?plain=1#L504-L513) says (emphasis added by me):

> Subscribe a method to be called for each **newly detected agent contact**.

The `connect.contact()` method adds an event listener that triggers under specific circumstances, it's not an asynchronous method with a callback argument. In other words, in your current code, every time you click the button, you're adding **a new listener** that will execute, when **a new contact comes in**. For example, if you start your application, click the button two times, **and then** start a chat and accept it, the following will occur:

- The browser will send `"Hi Colleague (...)"`.
- The browser will send `"SO and SO"` one time.
- The browser will send `"SO and SO"` a second time.

What you want is to subscribe once to the event, get a reference to the chat session(s), and use them when the user clicks the button. I see that you're using Angular, so an possible example may look like the following:

```ts
@Component({
  template: "<div #ccpContainer></div>",
  // (...)
})
class AmazonConnectCcpComponent implements AfterViewInit, OnDestroy {
  private readonly sessions: Map<string, connect.AgentChatSession>;

  @ViewChild("ccpContainer")
  private ccpContainer!: ElementRef<HTMLDivElement>;

  private selectedSession: connect.AgentChatSession | undefined;

  constructor() {
    this.sessions = new Map();
  }

  ngAfterViewInit(): void {
    // initialize amazon connect streams
    connect.core.initCCP(this.ccpContainer.nativeElement, {
      // ...
    });

    // on every incoming chat contact...
    connect.contact((contact) => {
      if (contact.getType() === connect.ContactType.CHAT) {
        // when the contact is accepted, store the chat session
        contact.onAccepted(async () => {
          const cnn = contact.getAgentConnection();
          if (cnn) {
            const session = await cnn.getMediaController();
            this.sessions.set(contact.contactId, session);
          }
        });

        // when the contact ends, cleanup the chat session
        contact.onEnded(() => {
          // cleanup chat session event handlers
          this.sessions.get(contact.contactId)?.cleanUpOnParticipantDisconnect();
  
          // remove the session from the map
          this.sessions.delete(contact.contactId);
        });
      }
    });

    // when the selected contact changes, update the selected session
    connect.core.onViewContact((event) => {
      this.selectedSession = this.sessions.get(event.contactId);
    });
  }

  ngOnDestroy(): void {
    // cleanup chat sessions
    for (const session of this.sessions.values()) {
      session.cleanUpOnParticipantDisconnect();
    }
    this.sessions.clear();
    this.selectedSession = null;

    // unitialize amazon connect streams
    connect.core.terminate();
  }

  async sendMessage(): Promise<void> {
    if (!this.selectedSession) {
      return; // or throw Error
    }

    await this.selectedSession.sendMessage({
      contentType: "text/plain",
      message: "SO and SO",
    });
  }
}
```

**_Disclaimer:_** I have not tested this code so the may be one or more typescript/syntax error and/or bugs. However, the idea is what matters.

**Comment by nayabrasool4910** [comment]
Thanks @marcogrcr for your valuable comment and explanation.
