### ISSUE TITLE
TypeScript typings are outdated

### ISSUE THREAD

**Issue by marcogrcr** [amazon-connect/amazon-connect-chatjs#138]
**Problem:**

The TypeScript typings in `index.d.ts` are outdated:

1. `sendMessage()` does not allow `{ contentType: "application/json" }`:

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/src/index.d.ts#L210-L215

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/src/index.d.ts#L514-L520

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/src/index.d.ts#L294-L296

2. `sendEvent()` does not allow `{ contentType: "application/vnd.amazonaws.connect.event.message.delivered" }` or `{ contentType: "application/vnd.amazonaws.connect.event.message.read" }` nor it models the `{ content: { messageId: string } }` body:

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/src/index.d.ts#L177-L182

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/src/index.d.ts#L542-L551

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/src/index.d.ts#L286-L292

3. `ChatSession.prototype.onDeliveredReceipt()` and `ChatSession.prototype.onReadReceipt()` are not typed:

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/src/core/chatSession.js#L87-L93

4. `ChatSession.prototype.onParticipantIdle()`, `ChatSession.prototype.onParticipantReturned()` and `ChatSession.prototype.onAutoDisconnection()` are not typed:

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/src/core/chatSession.js#L107-L117

5. `ChatSession.setGlobalConfig()` does not have typings for `{ loggerConfig: { customizedLogger, useDefaultLogger }, features }`:

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/README.md?plain=1#L83-L106

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/src/index.d.ts#L25

https://github.com/amazon-connect/amazon-connect-chatjs/blob/d85c5175d6576a60b6cad2a7b94196116864f4b1/src/index.d.ts#L96-L108

**Proposed fix:**

Update the `index.d.ts` to be in sync with the latest features.

**Comment by spencerlepine** [comment]
+1 we should create note/checkmark on `PULL_REQUEST_TEMPLATE.md`

**Comment by mliao95** [comment]
We are working on auto-generating `index.d.ts` which should resolve this issue.

**Comment by spencerlepine** [comment]
Working on small change in #163 for now - auto generating `index.d.ts` will require more refactors/updates.

**Comment by spencerlepine** [comment]
Change to auto-generate `*.d.ts` in `dist/` folder has been merged. This can introduce backward incompatible types, since many will use `any` declarations. Because of this, latest change has introduced `amazon-connect-chatjs@2.0.0` major bump.

Team will continue working on full TypeScript migration with conversion to `.ts` file extension.

**Comment by spencerlepine** [comment]
Latest release of `amazon-connect-chatjs@~2.0.0` includes change to auto-generate `index.d.ts`, which should unblock this issue.

Team is working on TypeScript migration with proper type declarations, but these will use `any` in the meantime.

Resolving.

Thanks,
Spencer
