### ISSUE TITLE
Adding @types Definition

### ISSUE THREAD

**Issue by Christian-Sesta** [amazon-connect/amazon-connect-chatjs#15]
It would be good to have `@types/amazon-connect-chatjs` similar to how there is a `@types/amazon-connect-streams` types library.

**Comment by Christian-Sesta** [comment]
Just wondering what's happening with this referenced PR Amazon team. It's been approved almost 2 months ago without any info since then. :/

**Comment by cassieyrh** [comment]
I see the above commit has been merged. When will ```@types/amazon-connect-chatjs``` be available?

**Comment by alim907** [comment]
Just wanted to follow up and check if there are any updates here or an ETA for when the type package will be available.

**Comment by tscheuneman** [comment]
The commit above has been merged, the typing should be available as part of the core package.
