### ISSUE TITLE
connectionDetails value not accessible, seems to not be assigned properly & types don't match

### ISSUE THREAD

**Issue by Qommission** [amazon-connect/amazon-connect-chatjs#154]
`connectionDetails` property is seemingly never initialised, meaning connectionToken wasn't accessible on a chat session. The chatDetails property in onConnectionEstablished and also the getChatDetails() method referenced a connectionToken in the types but it was never available.

Submitted a PR for this a while back but opening an issue in hopes this gets seen, the PR is here:
https://github.com/amazon-connect/amazon-connect-chatjs/pull/111
although this may have conflicts given there have been new versions released since this was created.

**Comment by spencerlepine** [comment]
Hi @Qommission, team will review and track this fix in backlog.

We will keep this issue open until new release of `amazon-connect-chatjs`, and provide update to this issue here.

Thanks,
Spencer

**Comment by spencerlepine** [comment]
Latest release of `amazon-connect-chatjs@^2.0.0` includes fix. Resolving
