### ISSUE TITLE
Typo on 'throttleTime' property when trying to call 'setGlobalConfig'

### ISSUE THREAD

**Issue by Qommission** [amazon-connect/amazon-connect-chatjs#155]
There is a typo at https://github.com/amazon-connect/amazon-connect-chatjs/blob/8795c8681bb089d6a24de79d76a38e97893f670c/src/core/chatSession.js#L194 when trying to reference the throttleTime property and also the `features` property on the `setGlobalConfig` params aren't typed.

Even accomodating for the typo when setting the features, the feature still seems to be a bit temperamental. There's a lack of types to handle the `message.delivered` & `message.read` events and the `sendEvent` call when using these events seem to have issues sometimes where it believes that messageReceipts haven't been enabled even when calling setGlobalConfig as recommended by the documentation (and also accomodating for the throttleTime typo). 

There are some hacky workarounds that have been possible but the feature seems to be a bit temperamental.

**Comment by spencerlepine** [comment]
Hi @Qommission, I have raised small PR to address this issue: #164 

There is also another PR in progress (https://github.com/amazon-connect/amazon-connect-chatjs/pull/163) to address missing typings.

This will not address major refactors to the feature or updates to documentation, that is separate work team will look into.

Thanks,
Spencer

**Comment by spencerlepine** [comment]
Change has been merged in #164 , will be included in next release to npm.
