### ISSUE TITLE
Docs to built custom UI for agent chat?

### ISSUE THREAD

**Issue by VaibhavKakadeHS** [amazon-connect/amazon-connect-chatjs#16]
My use case is I want to create custom chat UI for the agent and end user. I have working end user chat deployed using cloud formation template.
Now, I want to create a custom chat for the agent on my webpage. 
I am referring to the docs and not able to figure out where would following data come from.
```javascript
args = {
  "chatDetails": {
    "ContactId": "string", // I can get this from streams using connection object
    "ParticipantId": "string", // Where do I get this?
    "ParticipantToken": "string" // Where do I get this?
  },
  "type": connect.ChatSession.SessionTypes.AGENT,
  "options": {
    region: "string"
  },
  "websocketManager": WebSocketManager // Where do I get this?
};

var chatSession = connect.ChatSession.create(args);
```

**Comment by marcogrcr** [comment]
@VaibhavKakadeHS:

You will need to invoke the [StartChatContact](https://docs.aws.amazon.com/connect/latest/APIReference/API_StartChatContact.html) API. Note that this operation is protected with [SigV4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html). Here's two ideas of of how invoke it:

1. **Preferred:** Create your own API (e.g. [API Gateway](https://aws.amazon.com/api-gateway/) + [Lambda](https://aws.amazon.com/lambda/)) that calls this API and returns the `ParticipantId` and `ParticipantToken` values.
1. Use [Cognito](https://aws.amazon.com/cognito/) and [`aws-sdk`](https://www.npmjs.com/package/aws-sdk)'s ([`Connect.startChatContact()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Connect.html#startChatContact-property) + [`CognitoIdentityCredentials`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html)) to create the chat contact.

---

Here's an official example of option 1: [amazon-connect/amazon-connect-chat-ui-examples/cloudformationTemplates/startChatContactAPI](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/startChatContactAPI)

**Comment by VaibhavKakadeHS** [comment]
@marcogrcr Thanks for the reply. I actually used the following method to get the required details
```
ContactId = connection.contactId
ParticipantId = "random string for now"
ParticipantToken = connection.getConnectionToken()
websocketManager = connect.WebSocketManager 
```

**Comment by marcogrcr** [comment]
@VaibhavKakadeHS: Gotcha, I missed the **agent** portion of your question. For the agent, you'll probably want to use [`chatConnection.getMediaController()`](https://github.com/amazon-connect/amazon-connect-streams/blob/1.4.8/Documentation.md#chatconnectiongetmediacontroller). That being said, there are some caveats with that API. See `amazon-connect-streams`' [#261](https://github.com/amazon-connect/amazon-connect-streams/issues/261) for more info.

**Comment by ctwomblyamzn** [comment]
Hi, I just wanted to reinforce @marcogrcr's answer. Yes, you should use `chatConnection.getMediaController()`. It returns the `ChatSession` class documented in the [`amazon-connect-chatjs` docs](https://github.com/amazon-connect/amazon-connect-chatjs). Let me know if you have any further questions.
