### ISSUE TITLE
IE11 support for chatjs

### ISSUE THREAD

**Issue by mydatahack** [amazon-connect/amazon-connect-chatjs#17]
It looks like IE11 is not supported. There seems to be something wrong with the websocket method once the connection is established and we cannot see any message coming through with onMessage(). Can anyone advise us what to do, please?

**Comment by matthewhartman** [comment]
@labelson are you able to comment on the above? Furthermore, is there a table of supported browsers for this chat bot?

**Comment by mydatahack** [comment]
All good. This piece of code will help you.

```javascript
document.addEventListener('DOMContentLoaded', () => {
  if (isIE) {
    window.location.replace("https://www.google.com.au/chrome/");
  }
});
function isIE() {
  ua = navigator.userAgent;
  var is_ie = ua.indexOf("MSIE ") > -1 || ua.indexOf("Trident/") > -1;
  return is_ie; 
}
```

**Comment by spencerlepine** [comment]
Hi @mydatahack , any updates on this issue? If so, could you provide more steps to reproduce please.

Is this related to a WebSocketManager issue #42 and the `navigator.onLine` support ([caniuse.com/online-status](https://caniuse.com/online-status))?

Want to check if there are any further issues if we need to keep this open.

Thanks,
Spencer

**Comment by spencerlepine** [comment]
Documentation does not list this under [supported browsers](https://docs.aws.amazon.com/connect/latest/adminguide/add-chat-to-website.html), ChatJS does not currently have test coverage or official support for IE11.

Resolving this issue, please feel free to re-open or reach out if there are further questions.

Thanks,
Spencer
