### ISSUE TITLE
Facing Issue when working with multimedia messages

### ISSUE THREAD

**Issue by SaqibOctave** [amazon-connect/amazon-connect-chatjs#187]
Hi, 
I am trying to get the Multimedia URL of S3, For that we use getAttachment API of amazon connect. I am using amazon-connect-chatjs, In these streams there is a method name downloadAttachment.This downloadAttachment method Wraps the [GetAttachment](https://docs.aws.amazon.com/connect-participant/latest/APIReference/API_GetAttachment.html) API. I invoke this method to get the URL, 
What I Expect:
```
try{
                  const chatAttachmentResponse = await controller.downloadAttachment({
                    attachmentId: response.data.Attachments[0].AttachmentId,
                  })
                  console.log("chatAttachmentResponse :: ", chatAttachmentResponse);
                  const { attachment } = chatAttachmentResponse.data;


                  console.log("atachment Response :: ", attachment);
                }catch(e){
                  console.log(e)
```
When it hit this method I expect The response like [Response](https://docs.aws.amazon.com/connect-participant/latest/APIReference/API_GetAttachment.html#API_GetAttachment_ResponseSyntax).
What I got:
When above method hit it return a Blob and starts downloading the file directly.

**Comment by mliao95** [comment]
Hi @SaqibOctave!

The functionality of [downloadAttachment](https://github.com/amazon-connect/amazon-connect-chatjs/blob/master/src/client/client.js#L215) is to call the ACPS (Amazon Connect Participant Service) GetAttachment API to get the URL and automatically download it. The methods in `amazon-connect-chatjs` leverage ACPS APIs but are not direct mirrors.

If your use case requires the direct use of ACPS APIs, you would have to call that directly: https://docs.aws.amazon.com/connect-participant/latest/APIReference/working-with-acps-api.html

Let me know if you have any other questions!

**Comment by SaqibOctave** [comment]
@mliao95 i tried to run the sendAttachment method of amazon-connect-chatjs but there is a problem with that 
![image](https://github.com/amazon-connect/amazon-connect-chatjs/assets/110086158/46b264a4-efba-495e-8113-e106a1e0c684)
the first API is called successfully but when it go to call complete-attachment-api it gives an error like 
![image](https://github.com/amazon-connect/amazon-connect-chatjs/assets/110086158/f5f83eb4-3797-4c08-8b86-8be442ce1891)
would you please help me that how to run these API directly in an angular project?

**Comment by SaqibOctave** [comment]
I have Used get Attachment API in angular but didn't know how to use in angular Please share if you have any Idea.
