### ISSUE TITLE
Send attachment throw error that signature does not match

### ISSUE THREAD

**Issue by SaqibOctave** [amazon-connect/amazon-connect-chatjs#188]
Hi All,
I try to invoke the sendAttachment method of the streams API, but when i pass the Attachment to Send Attachment API it through an error that signtaure does not match 
```
controller.sendAttachment({
                    attachment: file
                  }).then((res)=>{
                    console.log(res);
                  })
```
the First API runs successfully like this 
![image](https://github.com/amazon-connect/amazon-connect-chatjs/assets/110086158/a945da5c-bbab-438d-a50c-d1c79d287903)
and the response of the start-attachment-upload API is exact match like in the documentation
```
{
    "AttachmentId": "a9ac98ec-c936-4441-a124-9d7a88debfce",
    "UploadMetadata": {
        "HeadersToInclude": {
            "x-amz-meta-contact_id": "3dff5a86-2f3a-4bf3-aa47-d82871671096",
            "x-amz-meta-initial_contact_id": "3dff5a86-2f3a-4bf3-aa47-d82871671096",
            "x-amz-acl": "bucket-owner-full-control",
            "Content-Disposition": "attachment; filename=\"56102_file.txt\"",
            "x-amz-meta-account_id": "747926693930",
            "Content-Length": "9",
            "Content-Type": "text/plain",
            "x-amz-meta-organization_id": "84ecefa9-184a-400f-babf-3288d7c8fd04"
        },
        "Url": "URL",
        "UrlExpiry": "2023-08-03T08:15:46Z"
    }
}
```
but when it goes to complete attachment upload part it gives the error:
![image](https://github.com/amazon-connect/amazon-connect-chatjs/assets/110086158/346526fa-b29b-4802-9879-2fcf0a1f7e8c)

**Comment by mhiaror** [comment]
[SaqibOctave](https://github.com/SaqibOctave) I tried out the `sendAttachment` API call, it seems to be working for me. 
Its a 3 step process:
1. Call `start-attachmend-upload` - this works for you based on screenshot you attached.
2. Call s3 pre-signed URL to upload the attachment -- I see from screenshot you attached - this is failing! 
Can you please follow the documentation here https://docs.aws.amazon.com/connect/latest/adminguide/enable-attachments.html
to make sure your S3 bucket is configured correctly to enable attachments support.
