### ISSUE TITLE
chatSession.getTranscript fails when scanDirection === "FORWARD"

### ISSUE THREAD

**Issue by marcogrcr** [amazon-connect/amazon-connect-chatjs#19]
According to [`chatSession.getTranscript`'s documentation](https://github.com/amazon-connect/amazon-connect-chatjs/tree/1.0.6#chatsessiongettranscript), this is a valid request:

```js
await chatSession.getTranscript({
  scanDirection: "FORWARD"
});
```

However, I get the following error:

```js
{
  type: "ValidationException",
  message: "Validation exception due to invalid parameter",
  stack: /* ... */,
  metadata: null
}
```

When I check the network request, here's what I see (headers omitted for simplification):

**Request:**

```http
POST /participant/transcript HTTP/1.1
host: participant.connect.us-east-1.amazonaws.com
content-type: application/json

{
  "MaxResults": 15,
  "ScanDirection": "FORWARD",
  "SortOrder": "ASCENDING",
  "StartPosition": {}
}
```

**Response:**

```http
HTTP/1.1 400
content-type: application/json

{
  "message": "Validation exception due to invalid parameter"
}
```

**Environment:**

- `amazon-connect-chatjs`: 1.0.6

**Comment by ctwomblyamzn** [comment]
I was able to reproduce this issue, and we are investigating. I will update this ticket once we know more.

**Comment by ctwomblyamzn** [comment]
Got some clarification about this API usage. The AWS docs are a bit vague. See my pull request. https://github.com/amazon-connect/amazon-connect-chatjs/pull/21
