### ISSUE TITLE
Callbacks not called when its mounted next time

### ISSUE THREAD

**Issue by AnilSonix** [amazon-connect/amazon-connect-chatjs#199]
I am using ccp panel in react app
The panel is mounted successfully , and corresponding callbacks also like onAuthorizeSuccess , onInitialized etc calls working properly

But after I navigate to another page, I terminate the ccp panel.
But it complains that iframe dom node is not found (as react completely removed the dom node when navigated to different page).

Next time, when I come to ccp page, it init the ccp panel again , it gets mounted, **but this time callbacks are not called.**

How can I use this with the react ecosystem?

**Comment by spenlep-amzn** [comment]
Hi @AnilSonix,

It appears this issue is related to StreamsJS API and embeded CCP. We own ChatJS, which does not control any iframe logic.

Please direct this towards the owners and raise an issue here: https://github.com/amazon-connect/amazon-connect-streams/issues

Thanks
-S😍pencer

**Comment by AnilSonix** [comment]
Thanks, I added there also
 https://github.com/amazon-connect/amazon-connect-streams/issues/806
