### ISSUE TITLE
Download Attachment Returning Blob istead of S3 pre-signed URL

### ISSUE THREAD

**Issue by OctaveIdeas** [amazon-connect/amazon-connect-chatjs#201]
I am using connect stream with angular i have setup the custom CCP for Chat widget. plain messages are working perfectly fine. but when i sent Media message through streams it returns an attachment ID, I invoke the downland attachment api and pass the attachment Id as a parameter. 
What i expect:
I expect in response it deliver the S3 URL, as mentioned in the Document. 
What i get:
I get the blob in response of download attachment Api 
`const chatAttachmentResponse = await controller.downloadAttachment({
                    attachmentId: response.data.Attachments[0].AttachmentId
                  });
                  console.log("Download Attachment Responmse is :: ", chatAttachmentResponse);`
                 Response :
                 
![image](https://github.com/amazon-connect/amazon-connect-chatjs/assets/126852001/b178d4ca-c3b5-4489-9e45-e1a543c2aea1)

**Comment by spenlep-amzn** [comment]
Hi @OctaveIdeas,

ChatJS is working as expected. ChatJS is a wrapper around the JavaScript AWS SDK, so it contains additional logic. The actual [GetAttachment](https://docs.aws.amazon.com/connect-participant/latest/APIReference/API_GetAttachment.html) API will return the S3 url. 

`downloadAttachment()` will return the actual file as mention in the [README doc](https://github.com/amazon-connect/amazon-connect-chatjs?tab=readme-ov-file#chatsessiondownloadattachment). It will get the url AND download, please refer to this code block: [[ref](https://github.com/amazon-connect/amazon-connect-chatjs/blob/cef17c302e2c83cb7f31c6125e9e53b34f354bbc/src/client/client.js#L230-L252)]

Going to resolve this issue now. Please feel free to open further issues or comment if documentation is unclear
Thank you,
-Spencer
