### ISSUE TITLE
Purpose of connect.ChatSession.connect args metadata property

### ISSUE THREAD

**Issue by Christian-Sesta** [amazon-connect/amazon-connect-chatjs#23]
I was curious if there was more information on what the purpose of this metadata object is as the documentation is pretty lacking in that regard. Will it ever be used to set contact flow attributes down the line?

I have a requirement around collecting some user details before starting a chat session and it would be good to have the ability to pass them to contact flow via this property. If that is not possible I am assuming the best way to pass this properties to the contact flow is straight after the `StartChatContact` call by using the `UpdateContactAttributes` endpoint.

**Comment by spencerlepine** [comment]
Hi @Christian-Sesta , any updates on this issue?

I am seeing updates to the README since this was raised. Were you able to implement this for your use case?

If not team should re-review README/documentation.

Want to check if there are any further issues if we need to keep this issue open.

Thanks,
Spencer

**Comment by Christian-Sesta** [comment]
@spencerlepine This was raised many years ago now and my team has moved off of this. However the fix was to use the property field as part of `StartChatContact` to set the contact attributes. I assumed that is what this metadata property was going to be used for, but that was wrong as its only meant to keep some form of cached state for the custom chat widget itself. Feel free too close.

**Comment by spencerlepine** [comment]
Okay, was guessing that since this has been open for a long time. I will resolve the issue, thanks for the prompt reply!

Thanks,
Spencer
