### ISSUE TITLE
`getTranscript()` not working for other contactIds

### ISSUE THREAD

**Issue by tjw0051** [amazon-connect/amazon-connect-chatjs#28]
Previously it was possible to fetch the transcript for a different `contactId` than the currently connected contact. However now when I call `getTranscript()` for a valid contactId (with full transcript available through the Amazon Connect dashboard) i get a response like:
```
{
    "InitialContactId": "...",
    "NextToken": "",
    "Transcript": []
}
```
Is it no longer possible to get the transcript for a different contactId?

**Comment by tscheuneman** [comment]
Hi @tjw0051, sorry for the late response to this.  ChatJs implements the public Amazon Connect Participant Service API's as described here:

https://docs.aws.amazon.com/connect-participant/latest/APIReference/API_GetTranscript.html

**Comment by tscheuneman** [comment]
Closing this, feel free to reopen if you have any other questions.
