### ISSUE TITLE
Multiple calls to _fetchConnectionDetails and therefore participant connection

### ISSUE THREAD

**Issue by thornleyk** [amazon-connect/amazon-connect-chatjs#31]
Hi, we have observed the chat js library making multiple calls, sometimes up to 3 calls, to the participant connection endpoint.  Apart from adding to the overall latency of the connection, this seems to impact clients by potentially generating throttling responses from connect.  I have a fix for this just raising the issue before the pull request

**Comment by thornleyk** [comment]
Closed as per provided AWS merge

**Comment by thornleyk** [comment]
The latest build seems to have broken the websocket connection.  We still get 2 participant/connection requests but on the second call we now get "Connection Broken" on the websocket call.  As my merge request was not taken Its very hard to see the individual fixes that effected the build in #34.

**Comment by thornleyk** [comment]
Ok I have found that we are getting status NeverStarted error from the WebSocket call onInitFailure in LpcConnectionHelper. the Websocket creds and URL look good as I can connect to them directly. The LpcConnectionHelper and WebSocket Manager are not happy though 
![Screen Shot 2020-10-06 at 10 05 36 PM](https://user-images.githubusercontent.com/11580279/95181730-248b0b80-0820-11eb-954c-37d5987f15e7.png)

**Comment by vertic4l** [comment]
Got a similar issue with it. Calling `disconnectParticipant` triggers 2 requests:

<img width="549" alt="Bildschirmfoto 2021-02-15 um 10 53 52" src="https://user-images.githubusercontent.com/1771763/107931138-2908c300-6f7c-11eb-8059-806a27549c6b.png">

**Comment by tscheuneman** [comment]
@thornleyk Are you still observing these multiple calls?

@vertic4l The two requests are likely a OPTIONS call as well as the POST call.

**Comment by mhiaror** [comment]
There is a retry logic in `ChatJS` - if an API request fails , we retry it 3 times. 
Also, multiple calls to fetchConnectionDetails is fixed in the latest release
