### ISSUE TITLE
Build process issues

### ISSUE THREAD

**Issue by chrishart0** [amazon-connect/amazon-connect-chatjs#33]
I've run into a few issues during the build process and will document them + their fixes here so the documentation in the readme may be updated.

System Info:
* Windows 10
* Running commands from PowerShell
* Node Version: v12.18.4 (Latest LTS as of writing this ticket)

### Issue 1: Jest missing
Encountered this on step 4 of [Building](https://github.com/amazon-connect/amazon-connect-chatjs#building)
```
$ npm run devo

> amazon-connect-chatjs@1.0.6 devo C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs
> jest && webpack --mode=development

'jest' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amazon-connect-chatjs@1.0.6 devo: `jest && webpack --mode=development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the amazon-connect-chatjs@1.0.6 devo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MyUser\AppData\Roaming\npm-cache\_logs\2020-09-24T16_10_29_984Z-debug.log
```

#### Fix
`npm install -g jest`
Source: https://stackoverflow.com/questions/53638220/jest-error-jest-is-not-recognized-as-an-internal-or-external-command-operabl

### Issue 2:  Failed to write coverage reports:
Got this after running `npm run devo`
Got this after running `npm run release`
Got this after running `npm run test`
```
        Failed to write coverage reports:
        ERROR: Error: Path contains invalid characters: C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs\coverage\src\lib\webpack:\webpack
        STACK: Error: Path contains invalid characters: C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs\coverage\src\lib\webpack:\webpack
    at checkPath (C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs\node_modules\make-dir\index.js:21:18)
    at Function.module.exports.sync (C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs\node_modules\make-dir\index.js:91:2)
    at FileWriter.writeFile (C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs\node_modules\istanbul-lib-report\lib\file-writer.js:190:12)
    at HtmlReport.onSummary (C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs\node_modules\istanbul-reports\lib\html\index.js:213:44)
    at Visitor.<computed> [as onSummary] (C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs\node_modules\istanbul-lib-report\lib\tree.js:34:30)
    at ReportNode.Node.visit (C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs\node_modules\istanbul-lib-report\lib\tree.js:112:17)
    at C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs\node_modules\istanbul-lib-report\lib\tree.js:118:15
    at Array.forEach (<anonymous>)
    at ReportNode.Node.visit (C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs\node_modules\istanbul-lib-report\lib\tree.js:117:24)
    at Tree.visit (C:\Users\MyUser\Documents\GitHub\amazon-connect-chatjs\node_modules\istanbul-lib-report\lib\tree.js:150:20)
```

####Fix
Didn't bother to fix this. Looks like the issue is that the path has a : in it at _webpack:_. 

### Issue 3:  NPM Run Clean fail
```
$ npm run clean

> amazon-connect-chatjs@1.0.6 clean C:\Users\chart\Documents\GitHub\amazon-connect-chatjs
> rm -rf build/ node_modules build

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amazon-connect-chatjs@1.0.6 clean: `rm -rf build/ node_modules build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amazon-connect-chatjs@1.0.6 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chart\AppData\Roaming\npm-cache\_logs\2020-09-24T16_31_37_888Z-debug.log
```
####Fix
Didn't bother to fix this. Looks like clean is trying to use Unix style commands instead of PowerShell.

**Comment by spencerlepine** [comment]
Hi @chrishart0 , any updates on these issues?

For **issue 2**, this could be related to Windows path.

As far as I am seeing, `npm test` and `npm devo` are passing in ubuntu:
-  Passing in `Node LTS 10, 12, 14, and 15.x`: https://github.com/amazon-connect/amazon-connect-chatjs/actions/runs/4814095749
- Passing in `Node LTS 16, 18, and 19`: https://github.com/amazon-connect/amazon-connect-chatjs/actions/runs/4814101594 

For **issue 3**, this `rm <files>` command will run in Linux, but must use a Windows command similar to `del /f “filename"`.

If there are any further concerns please let us know. Would like to confirm before closing the issue.

Thanks,
Spencer

**Comment by spencerlepine** [comment]
Following Node LTS [[ref](https://nodejs.dev/en/about/releases/)], ChatJS (^1.5.0) is currently supported in Node v16+ (see #158). 

This issue is out-dated, going to resolve. Please feel free to re-open or reach out if there are further questions.
