### ISSUE TITLE
Non-minified example chat app?

### ISSUE THREAD

**Issue by winzig** [amazon-connect/amazon-connect-chatjs#4]
We've been evaluating a few different providers (Intercom, Twilio, etc) and AWS Connect seems the most configurable and fits our use case the best, but am disappointed that the only web chat client I've been able to find is this minified example here: https://github.com/amazon-connect/amazon-connect-chat-ui-examples

Is there a reason that sample is minified? Are there any other "official" AWS Connect web chat clients? Is there a plan to release anything soon in this regard, or an non-minified version of the sample UI that we can build off of?

**Comment by ctwomblyamzn** [comment]
Closing this because this was answered in another thread: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/issues/3
