### ISSUE TITLE
Connect not defined in vanilla JS

### ISSUE THREAD

**Issue by si3mshady** [amazon-connect/amazon-connect-chatjs#40]
I am attempting to serve CCP from flask and CCP will not load...
vanilla js. 
Uncaught ReferenceError: connect is not defined

When I the index.html is read as a file   file:///index.html it will load just fine.

**Comment by johnmryan** [comment]
Are you still experiencing this issue? Did you import the chatjs file in your html? 

The `index.js` will load the global connect object if it doesn't exist already. https://github.com/amazon-connect/amazon-connect-chatjs/blob/master/src/index.js#L4

**Comment by tscheuneman** [comment]
Closing, feel free to re-open if you have any other questions
