### ISSUE TITLE
Documentation for downloadAttachment

### ISSUE THREAD

**Issue by griffisc306** [amazon-connect/amazon-connect-chatjs#46]
The documentation is very vague for this. All that is returned for me is a blob, even though I seethe url object in network logs. Any advice on how to pass the URL

**Comment by ZeeshiM** [comment]
I'm Having the Same Issue. Getting Blob object in Console and URL in Network Tab response body is having URL to get the File Downloaded. Not getting the Expected response in console to download the Attachment shared.

**Comment by ZeeshiM** [comment]
> The documentation is very vague for this. All that is returned for me is a blob, even though I seethe url object in network logs. Any advice on how to pass the URL

I've done my Work using this method and working fine for me. Try this and let me know if doing so, solve your Problem. 

getAttachment(attachmentID, attachmentName) {
        console.log('Attachment ID Recieved', attachmentID);
        this.activeChat.controller.downloadAttachment({attachmentId: attachmentID })
        .then((res, req) => {
			console.log('Attachment response',res);
			let fileUrl = window.URL.createObjectURL(res);
			console.log('CreateObjectURl', fileUrl);
			var link = document.createElement('a');
			link.href = fileUrl;
			link.download = attachmentName;
			link.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true, view: window }));
        }).catch((error) => {
            console.error(`[Attachment Failed] `, error);
        });
	}

**Comment by griffisc306** [comment]
You are a life saver! That did the trick!

**Comment by ZeeshiM** [comment]
You're welcome. 🙂
