### ISSUE TITLE
Any support for "response buttons"?

### ISSUE THREAD

**Issue by winzig** [amazon-connect/amazon-connect-chatjs#5]
Is there any support with the Chat SDK for supplying "response buttons" that users can choose to avoid having to type common requests out, such as shown here from Amazon's own support chat system:

<img width="521" alt="Screen Shot 2019-12-22 at 1 49 22 PM" src="https://user-images.githubusercontent.com/127062/71327805-f2433400-24c1-11ea-9bbc-e8805ad47c2f.png">

**Comment by ctwomblyamzn** [comment]
Hello! There is no support at this time with the Chat SDK for supplying "Response buttons". You would have to implement this feature yourself. We will consider this suggestion in the future. Thank you for the suggestion!

**Comment by ctwomblyamzn** [comment]
Closing because this was answered.
