### ISSUE TITLE
ParticipantRole  in API not working

### ISSUE THREAD

**Issue by johnaws** [amazon-connect/amazon-connect-chatjs#53]
i am creating a custom Chat application with help of   amazon-connect-chat (https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famazon-connect%2Famazon-connect-chatjs%2Fblob%2Fmaster%2Fdist%2Famazon-connect-chat.js&amp;data=04%7C01%7Cjohnalbert.d%40servion.com%7Cc2b1624ba35b4837345c08d8e3cdada6%7C0eb7ab7502264f22876b7b29fe557678%7C0%7C0%7C637509819844144821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=O7GFs4pkLqBwUnH%2FMBmqv2Bko1djQhZHF21H%2BYbWbaI%3D&amp;reserved=0) and connect-streams
After upgrading to latest version of  amazon-connect-chat, the chat functionality got broken

The ParticipantRole form API is always customer  "CUSTOMER" , when is received message is from Agent or customer,  so we are not able to identify if the received message is form agent or customer

Can you please help in resolving this issue

**Comment by johnmryan** [comment]
Hey @johnaws , are you able to provide a minimal code snippet to demonstrate this behavior? If you pass the `CUSTOMER` type when you create the chat session, your messages should come through as Customer side messages. 

https://github.com/amazon-connect/amazon-connect-chatjs/blob/97f73627839b02ef8d6db66746f811e5ed81f983/src/core/chatSession.js#L39

**Comment by johnaws** [comment]
Hey

This chat id from agent side, so when creating a chat instance we pass AGENT

Below is code snippet we use to create connection with customer

To the method we pass

ContactId: ""
ParticipantId: ""
ParticipantToken : ""

As chatDetails



CreateNewConnection(chatDetails) {
    var logger = {
      debug: (data) => {
        console.debug(data);
      },
      info: (data) => {
        console.info(data);
      },
      warn: (data) => {
        console.warn(data);
      },
      error: (data) => {
        console.error(data);
      },
    };

    var globalConfig = {
      loggerConfig: {
        logger: logger,
        level: connect.ChatSession.LogLevel.INFO,
      },
      //region: "us-west-2"
      //following is done to connect to psteam instance
      region: "us-east-1",
    };
    var socketManager = connect.core.getWebSocketManager();
    var promise = new Promise((resolve, reject) => {
      var args = {
        chatDetails: this.GetChatInstance(chatDetails.ContactId),
        type: connect.ChatSession.SessionTypes.AGENT,
        websocketManager: socketManager,
      };

      if (args.chatDetails == null) {
        resolve(null);
      }
      connect.ChatSession.setGlobalConfig(globalConfig);

      var chatClient = connect.ChatSession.create(args);
      try {
        chatClient
          .connect()
          .then((response) => {
           console.log("Chat is connected!");
            resolve(chatClient);
          })
          .catch((error) => {
            console.log("Could not connect.");
            resolve(null);
          });
      } catch (e) {
        resolve(null);
      }
    });
    return promise;
  }
}


Thanks
John

**Comment by tscheuneman** [comment]
Hi John, I don't think I'm fully understanding the problem you're experiencing here.  Are you trying to send messages from the agent side?  If so, the streams team might be able to help you more effectively https://github.com/amazon-connect/amazon-connect-streams

**Comment by tscheuneman** [comment]
Closing, feel free to re-open if you have any other questions
