### ISSUE TITLE
Getting an Error while trying to get connection for chat

### ISSUE THREAD

**Issue by cbgandhi** [amazon-connect/amazon-connect-chatjs#55]
Hi,

While trying to get connection (contact.getAgentConnection()) to create agent chat session in OnConnected event, getting following error in connect-stream.js -

Error - "AWS.ConnectParticipant is not a constructor"

I am importing the libs in following order:

<script src="https://sdk.amazonaws.com/js/aws-sdk-2.824.0.min.js"></script>
<script type="text/javascript" src="js/connect-streams.js"></script>
<script type="text/javascript" src="js/amazon-connect-chat.js"></script>

can you please help?

**Comment by JosephAMumford** [comment]
The documentation says:

> **Scenario 2: Streams and ChatJS are used. You are importing the AWS SDK.**
> 
> Import Streams, then ChatJS, then the SDK. Ensure that your AWS SDK includes the ConnectParticipant Service (it is relatively new, so make sure you have an up-to-date AWS SDK version [^2.597.0]).

I had issues with this at first too.  Hope that helps!

**Comment by cbgandhi** [comment]
Thank you, let me try.

**Comment by johnmryan** [comment]
Hey @cbgandhi , just checking in here. Did you have any luck with bumping the AWS SDK or adjusting import order?

**Comment by johnmryan** [comment]
Closed the issue for now assuming the solution worked for you, feel free to reopen if you are still having problems.
