### ISSUE TITLE
Bot name?

### ISSUE THREAD

**Issue by winzig** [amazon-connect/amazon-connect-chatjs#6]
I've created a Lex bot and hooked it up to a contact flow that I'm testing with the sample chat UI. Whenever my bot says something, the name shown above it is just "BOT". Where is the name of the bot controlled?

<img width="298" alt="Screen Shot 2019-12-22 at 1 56 09 PM" src="https://user-images.githubusercontent.com/127062/71327874-d12f1300-24c2-11ea-8e22-fa49b4ad09da.png">

**Comment by ctwomblyamzn** [comment]
Sorry for the delay! Currently this is set to always be BOT. As such, I labeled this as an enhancement request.

**Comment by coelhorrc** [comment]
It is weird that you can't even change by CSS because the classes used by the agent/bot are the same as the ones used by the client/customer

`<div class="sc-gipzik dRSldq"><div class="sc-csuQGl kXdihe"><div class="sc-Rmtcm">BOT</div><div class="sc-bRBYWo kHoeZK">1:34 PM</div></div><div direction="Incoming" class="sc-hzDkRC gnSJLy"><span class="Linkify">TEST BOT TALK</span></div></div>`

**Comment by manzanofab** [comment]
> Sorry for the delay! Currently this is set to always be BOT. As such, I labeled this as an enhancement request.

That will be amazing, just wondering how the suggestion is going nearly 3 years after? :)

**Comment by spencerlepine** [comment]
Hi all,

Confirming that we do not currently support customizing the `BOT` name in transcript.

> Neither [ChatJS](https://github.com/amazon-connect/amazon-connect-chatjs), [Streams](https://github.com/amazon-connect/amazon-connect-streams), or updating a [contact flow](https://docs.aws.amazon.com/connect/latest/adminguide/connect-contact-flows.html) support customizing BOT name

Team has existing work (no ETA yet) for a feature to customize BOT name in the UI. These changes would apply to the [out-of-the-box Chat widget](https://docs.aws.amazon.com/connect/latest/adminguide/add-chat-to-website.html).

Please refer to this issue for updates: https://github.com/amazon-connect/amazon-connect-chat-interface/issues/123

Closing this issue, as it will not be added to ChatJS.

Thanks,
Spencer
