### ISSUE TITLE
Getting chat transcript during ACW

### ISSUE THREAD

**Issue by cmrockwell** [amazon-connect/amazon-connect-chatjs#61]
Hi

I'm using ChatJS and Amazon Connect Streams with a slightly customized agent CCP. The agents want to be able to send the chat participants a follow-up email containing the transcript of their chat. 

Using the Amazon Connect Streams API my code looks like this

```
// When new contacts are created, this assigns a callback function
connect.contact(function(contact){    
    console.log("LSA: new contact, set AWC listener");
    contact.onACW(handleACW);
}); 
```

```
// The callback function
function handleACW(contact) {
    console.log("On contact AWC");
    var connection  = contact.getAgentConnection()
    connection.getConnectionToken()
                .then( function(r) { 
                    var token = r;
                    var creds = new AWS.Credentials('','');
                    var config = new AWS.Config({
                        region: "us-east-1",
                        endpoint: "https://participant.connect.us-east-1.amazonaws.com",
                        credentials: creds
                     });
                    var participant = new AWS.ConnectParticipant(config);
                    var params = {"MaxResults":100,"ScanDirection":"BACKWARD","SortOrder":"ASCENDING","StartPosition":{}}
                    params['ContactId'] = contact.contactId;
                    params['ConnectionToken'] = token.chatTokenTransport.participantToken;
                    participant.getTranscript(params, function(err, data) {
                        if (err) {
                            console.log("Transcript Error")
                            console.log(err, err.stack); // an error occurred
                        } else {
                            console.log("Transcript Success")
                            console.log(data);           // successful response
                        }
                    });
    });
}

```

The problem I have is that `participant.getTranscript` fails when called during ACW with the response being Access Denied. In my testing, this call only succeeds when registered on the `contact.onRefresh` event while the chat is actively in progress.

In speaking with Amazon technical support, they suggested raising the question here. Please let me know your ideas.

Thanks!

**Comment by spenlep-amzn** [comment]
Hi,

Unfortunately there is no way to retrieve the transcript after a contact has ended (due to the Connect architecture). You must make that `getTranscript` call during an ongoing chat.

**Possible Work Around:** since the chat has ended, a work-around could be [re-hydrating and starting a new chat](https://docs.aws.amazon.com/connect/latest/adminguide/chat-persistence.html), then calling the GetTranscript API. Starting a new chat is a bill-able event however.

Going to resolve this issue since there is no ChatJS change we could make to unblock this use case.

Thanks
-Spencer
