### ISSUE TITLE
Question about chatbox

### ISSUE THREAD

**Issue by bbolek** [amazon-connect/amazon-connect-chatjs#63]
Hello;
We are using chatbox and also we display some data to agent based on bot context. 
Is there any event that we can get, when user switches chats? For example in screenshot, agent has 2 chats, and when agent clicks to second chat, we want to display data about second contact. Is there a way to get contactid, when agent clicks that chat tab?

Thanks

![image](https://user-images.githubusercontent.com/1146456/122562904-3fb74780-d04c-11eb-9e8f-40160b41fff8.png)

**Comment by robmoores** [comment]
Have you tried using the Set Contact Attributes to get the Contact ID then the Set Whisper Flow block ?https://aws.amazon.com/premiumsupport/knowledge-center/connect-custom-whisper-flows-ivr/

**Comment by bbolek** [comment]
Hey robmoores thanks for your replly, 
I think connect.core.onViewContact() is doing what I want.

Have a great day.
