### ISSUE TITLE
client -> getTranscript - logging

### ISSUE THREAD

**Issue by mcosicaws** [amazon-connect/amazon-connect-chatjs#64]
In client.js -> getTranscript function, there's `console.log` at line 137
https://github.com/amazon-connect/amazon-connect-chatjs/blob/master/src/client/client.js#L137
which is polluting Console Log.

It should be replaced with `self.logger.info` so that this message is not logged when:
```javascript
loggerConfig: {
                level: window.connect.ChatSession.LogLevel.WARN
            }
```

**Comment by sseidel16** [comment]
@mcosicaws this should be fixed following [this](https://github.com/amazon-connect/amazon-connect-chatjs/pull/86) merge.
