### ISSUE TITLE
Access denied on chat events APIs.

### ISSUE THREAD

**Issue by ArslanAliDaim** [amazon-connect/amazon-connect-chatjs#90]
When an agent accepts a chat that has been declined/missed by the them. The chat APIs are returning an error with status code 403 (Access Denied). But the same API calls are working fine if the agent accepts the chat the first time it is presented. This is how I am making the calls.
![image](https://user-images.githubusercontent.com/97523488/182353488-aedd0199-4f36-48b3-a81c-9ddd8be77cfb.png)
![image](https://user-images.githubusercontent.com/97523488/182353614-7148c4fe-461f-4d4d-bf15-9ffdbaa4d170.png)
![image](https://user-images.githubusercontent.com/97523488/182353750-bbf7a9b8-45f7-48b3-a94b-6c574e8afd21.png)
![image](https://user-images.githubusercontent.com/97523488/182353952-1487502a-33fc-4776-ba11-8d65ccac55cf.png)

I have been struggling with it for sometime now. Any and all help is much appreciated.

Note : I have made sure to follow [Chatjs](https://github.com/amazon-connect/amazon-connect-chatjs) to the dot. And the looked into the possible causes of 403 and none of that is happening in my case.

**Comment by jiahaoyu6666** [comment]
Hi, could you please list the detail step by step so that we can reproduce this issue?
