### ISSUE TITLE
getTranscript issue for agent chat session

### ISSUE THREAD

**Issue by wanlimaa** [amazon-connect/amazon-connect-chatjs#94]
Hi, 
I ran into an issue with calling chatSession.getTranscript(). Different errors were found based on the way how I create chatSession.

1.
```
contact.onConnected( async () => {
                    const cnn = contact.getAgentConnection() as connect.ChatConnection
                    const agentChatSession = await cnn.getMediaController();

                    agentChatSession.getTranscript({
                      maxResults: 100,
                      sortOrder: "ASCENDING"
                    });
}
```
I got the below error:
POST https://participant.connect.na.amazonaws.com/participant/transcript net::ERR_NAME_NOT_RESOLVED

In this way, it seems like the invoke URL for getTranscript() is incorrect. The correct url should be ``https://participant.connect.us-east-1.amazonaws.com/participant/transcript`` for our connect instance

2. Thus, I changed to alternative way to create chatSession as below
```
contact.onConnected(async () => {
                    const cnn = contact.getAgentConnection() as connect.ChatConnection
                    
                    const agentChatSession = connect.ChatSession.create({
                        chatDetails: cnn.getMediaInfo(), // REQUIRED
                        options: { 
                          region: "us-east-1", // REQUIRED, must match the value provided to `connect.core.initCCP()`
                        },
                        type: connect.ChatSession.SessionTypes.AGENT, 
                        websocketManager: connect.core.getWebSocketManager() 
                      });

                     await agentChatSession.getTranscript({
                         maxResults: 100,
                         sortOrder: "ASCENDING"
                    });
}
```
Then I got the below error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getConnectionToken')
    at e.value (chatController.js:124:51)
    at n.value (chatSession.js:116:28)
    at PanelChatroom.componentWillLoad (panel-chatroom.entry.js:28:56)
    at safeCall (index-ef333fab.js:1582:36)
    at dispatchHooks (index-ef333fab.js:1347:23)
    at Array.dispatch (index-ef333fab.js:1329:28)
    at consume (index-ef333fab.js:2991:21)
    at flush (index-ef333fab.js:3046:9)
```

**Comment by williameliel** [comment]
@wanlimaa Can you share the [setGlobalConfig](https://github.com/amazon-connect/amazon-connect-chatjs#connectchatsessionsetglobalconfig) call? seems like the initial error seems to be related to an error in the region set call.

**Comment by spencerlepine** [comment]
Hi @wanlimaa,

Can you make sure you have configured the region correctly before making the getTranscript call? This in the [connect.ChatSession.create()](https://github.com/amazon-connect/amazon-connect-chatjs#connectchatsessioncreate) or [connect.ChatSession.setGlobalConfig()](https://github.com/amazon-connect/amazon-connect-chatjs#connectchatsessionsetglobalconfig).

For second option, can you confirm that you have correctly passed in `chatDetails` to `.create()` according to documentation? https://github.com/amazon-connect/amazon-connect-chatjs#connectchatsessioncreate

Going to resolve this issue as there does not appear to the code bug on ChatJS side.

Please feel free to re-open or reach out with further questions if this does not resolve.

Thanks,
Spencer
