### ISSUE TITLE
sendAttachment error

### ISSUE THREAD

**Issue by frwebdev** [amazon-connect/amazon-connect-chatjs#97]
I have a problem with the method in question  > **chatSession.sendAttachment()**
This is what is reported in the documentation:

**attachment object is the actual file that will be sent to agent from end-customer and vice versa.**
```
const awsSdkResponse = await chatSession.sendAttachment({
  attachment: attachment
})
```

I tried to send the **attachment** both as a File and as a Blob type.
In both cases I get this error

`TypeError: Cannot read properties of undefined (reading 'type')`

I have noticed that the documentation is quite vague about the attachments.

Has anyone used the method successfully and can you help me?

**Comment by haomingli2020** [comment]
Hi there,

You can refer to the `sendAttachment()` and `onFileInput()` functions in this [file](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/d8a303703508793258ccb37c2fa239f2423d69da/src/components/Chat/ChatComposer/ChatComposer.js#L241-L255).
Which basically takes in the file input when user uploads it and eventually calls the same `chatSession.sendAttachment()` in this repo - [ref](https://github.com/amazon-connect/amazon-connect-chat-interface/blob/d8a303703508793258ccb37c2fa239f2423d69da/src/components/Chat/ChatSession.js#L92).

**Comment by frwebdev** [comment]
Thank you, the problem was i didn't send attachment like an object with the right key "attachment".
